# Generated by Django 5.1.2 on 2024-11-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_admin_admin_id_alter_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('0', '男性'), ('1', '女性')], max_length=10, verbose_name='性别'),
        ),
    ]
